version: 0.2


phases:
  build:
    commands:
      - echo Entering Build.
      - aws --version
      - pip install -Iv awscli==1.14.34
      - aws --version
      - sudo pip install -U pyopenssl==0.13.1 pyasn1 ndg-httpsclient
      - aws appsync list-graphql-apis --debug
