version: 0.2


phases:
  build:
    commands:
      - echo Entering Build.
      - aws --version
      - pip install --upgrade awscli
      - aws --version
      - easy_install pyOpenSSl
      - easy_install ndg-httpsclient
      - easy_install pyasn1
      - uname -a
      - pip install requests
      - #aws appsync list-graphql-apis 
      - python test.py
