version: 0.2


phases:
  build:
    commands:
      - echo Entering Build.
      - aws --version
      - pip install --upgrade awscli
      - aws --version
      - apt-get install python -y
      - #aws appsync list-graphql-apis --debug
