version: 0.2


phases:
  build:
    commands:
      - echo Entering Build.
      - aws --version
      - pip install --upgrade awscli
      - aws --version
      - pip install urllib3
      - pip install requests
      - pip show requests
      - sudo pip install --upgrade pyOpenSSL
      - aws appsync list-graphql-apis --debug 
      - #python test.py
