version: 0.2


phases:
  build:
    commands:
      - echo Entering Build.
      - aws --version
      - pip install --upgrade awscli
      - aws --version
      - pip install PyOpenSSL 
      - uname -a
      - aws appsync list-graphql-apis 
